### ISSUE TITLE
Converting docker-compose environment variable

### ISSUE THREAD

**Issue by KrisTemmerman** [githubsaturn/captainduckduck#317]
Im pulling apart prisma to have it run as a standalone docker container
Hoever I ran into this environment config.

``` 
environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: 
            migrations: true
            rawAccess: true
```

I can't seem to add these variables to the container .
